name: Simmons Tobias Photo
favicon: null
layout_spectrum: 0.11851865169592202
typography_spectrum: 0.8178619900718331
title: Simmons Tobias Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#383838'
    - '#7d7d7d'
    - '#b1b1b1'
    - '#efefef'
  brandStrength: 0.8125
  lightness: 0.53254509344697
  saturation: 0.15117367217317224
  rhythmicContrast: 0.456397790228948
purpose: []
